/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package digital_office_management_system;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author USER
 */
public class AdminLogin_form extends javax.swing.JFrame {

    /** Creates new form AdminLogin_form */
    public AdminLogin_form() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        // create border for the username and password field
        Border field_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.blue);
        ID.setBorder(field_border);
        Password.setBorder(field_border);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelMin = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabelAdminId = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        jLabelPassword = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        jCheckBoxShowPass = new javax.swing.JCheckBox();
        jButtonLogin = new javax.swing.JButton();
        jLabelBackButton = new javax.swing.JLabel();
        jLabelCopyrightText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMin.setText(" -");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMinMouseExited(evt);
            }
        });
        jPanel1.add(jLabelMin);
        jLabelMin.setBounds(630, 10, 20, 22);

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelClose.setText(" X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseExited(evt);
            }
        });
        jPanel1.add(jLabelClose);
        jLabelClose.setBounds(660, 10, 20, 22);

        jLabelAdminId.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        jLabelAdminId.setForeground(new java.awt.Color(0, 102, 204));
        jLabelAdminId.setText("Admin ID:");
        jPanel1.add(jLabelAdminId);
        jLabelAdminId.setBounds(130, 300, 150, 30);

        ID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ID.setForeground(new java.awt.Color(153, 153, 153));
        ID.setText("XX-XX-XX-XXX");
        ID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                IDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                IDFocusLost(evt);
            }
        });
        jPanel1.add(ID);
        ID.setBounds(280, 300, 230, 30);

        jLabelPassword.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(0, 102, 204));
        jLabelPassword.setText("Password:");
        jPanel1.add(jLabelPassword);
        jLabelPassword.setBounds(130, 340, 110, 30);

        Password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Password.setForeground(new java.awt.Color(153, 153, 153));
        Password.setText("password");
        Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordFocusLost(evt);
            }
        });
        jPanel1.add(Password);
        Password.setBounds(280, 340, 230, 30);

        jCheckBoxShowPass.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxShowPass.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jCheckBoxShowPass.setText("Show Password");
        jCheckBoxShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxShowPassActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBoxShowPass);
        jCheckBoxShowPass.setBounds(530, 340, 130, 30);

        jButtonLogin.setBackground(new java.awt.Color(255, 255, 255));
        jButtonLogin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(0, 153, 0));
        jButtonLogin.setText("Log In");
        jButtonLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonLoginMouseExited(evt);
            }
        });
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLogin);
        jButtonLogin.setBounds(180, 410, 350, 60);

        jLabelBackButton.setBackground(new java.awt.Color(255, 255, 255));
        jLabelBackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_icon.png"))); // NOI18N
        jLabelBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBackButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBackButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBackButtonMouseExited(evt);
            }
        });
        jPanel1.add(jLabelBackButton);
        jLabelBackButton.setBounds(20, 40, 25, 25);

        jLabelCopyrightText.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCopyrightText.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelCopyrightText.setForeground(new java.awt.Color(153, 153, 153));
        jLabelCopyrightText.setText("Copyright 2019 - Digital Office Management System | All Rights Reserved TO US");
        jPanel1.add(jLabelCopyrightText);
        jLabelCopyrightText.setBounds(90, 630, 530, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AdminLogin.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 702, 680);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusGained
        // clear the password field on focus if the text is "password"
        // get the password text
        String pass = String.valueOf(Password.getPassword());
        if(pass.trim().toLowerCase().equals("password"))
        {
            Password.setText("");
            Password.setForeground(Color.black);
        }
    }//GEN-LAST:event_PasswordFocusGained

    private void PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusLost
        // if the password field is equal to password or empty
        // we will set the "password" text in the field
        // on focus lost event
        // get the password text
        String pass = String.valueOf(Password.getPassword());
        if(pass.trim().equals("") || pass.trim().toLowerCase().equals("password"))
        {
            Password.setText("password");
            Password.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_PasswordFocusLost

    private void IDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDFocusGained
        // clear the textfield on focus if the text is "XX-XX-XX-XXX"
        if(ID.getText().trim().toUpperCase().equals("XX-XX-XX-XXX"))
        {
            ID.setText("");
            ID.setForeground(Color.black);
        }
    }//GEN-LAST:event_IDFocusGained

    private void IDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDFocusLost
        // if the text field is equal to username or empty
        // we will set the "XX-XX-XX-XXX" text in the field
        // on focus lost event
        if(ID.getText().trim().equals("") || ID.getText().trim().toUpperCase().equals("XX-XX-XX-XXX"))
        {
            ID.setText("XX-XX-XX-XXX");
            ID.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_IDFocusLost

    private void jButtonLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginMouseEntered
        // set jbutton background
        jButtonLogin.setBackground(new Color(149,165,166));
    }//GEN-LAST:event_jButtonLoginMouseEntered

    private void jButtonLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginMouseExited
        // set jbutton background
        jButtonLogin.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_jButtonLoginMouseExited

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        PreparedStatement st;
        ResultSet rs;        
        
        String id = ID.getText();
        String pass = String.valueOf(Password.getPassword());
        
        String query = "SELECT * FROM `admin` WHERE `Id` = ? AND `Password` = ?";
        
        // show a message if the id or the password fields are empty
        if(id.trim().equals("XX-XX-XX-XXX"))
        {
            JOptionPane.showMessageDialog(null, "Enter Your User ID", "Empty User ID", 2);
        }
        else if(pass.trim().equals("password"))
        {
            JOptionPane.showMessageDialog(null, "Enter Your Password", "Empty Password", 2);
        }
        else
        {
            try {
            st = MyConnection.getConnection().prepareStatement(query);
            
            st.setString(1, id);
            st.setString(2, pass);
            rs = st.executeQuery();
            
            if(rs.next())
            {
                String un = rs.getString("Username");
                AdminHomePage adhpg = new AdminHomePage(un);
                adhpg.setVisible(true);
                adhpg.pack();
                adhpg.setLocationRelativeTo(null);
                this.dispose();
                
            }else{
                JOptionPane.showMessageDialog(null, "Invalid User ID / Password", "Login Error", 2);
                ID.setText("");
                Password.setText("");
            }
            
            } catch (SQLException ex) {
                Logger.getLogger(Login_form.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseEntered
        jLabelClose.setForeground(Color.red);
    }//GEN-LAST:event_jLabelCloseMouseEntered

    private void jLabelCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseExited
        jLabelClose.setForeground(Color.black);
    }//GEN-LAST:event_jLabelCloseMouseExited

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jLabelMinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseEntered
        jLabelMin.setForeground(Color.gray);
    }//GEN-LAST:event_jLabelMinMouseEntered

    private void jLabelMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseExited
        jLabelMin.setForeground(Color.black);
    }//GEN-LAST:event_jLabelMinMouseExited

    private void jLabelBackButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackButtonMouseEntered
        jLabelBackButton.setBackground(Color.gray);
    }//GEN-LAST:event_jLabelBackButtonMouseEntered

    private void jLabelBackButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackButtonMouseExited
        jLabelBackButton.setBackground(Color.white);
    }//GEN-LAST:event_jLabelBackButtonMouseExited

    private void jLabelBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackButtonMouseClicked
        AdminOrStaff_form adorstf = new AdminOrStaff_form();
        adorstf.setVisible(true);
        adorstf.pack();
        adorstf.setLocationRelativeTo(null);
        adorstf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelBackButtonMouseClicked

    private void jCheckBoxShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxShowPassActionPerformed
        if(jCheckBoxShowPass.isSelected())
        {
            Password.setEchoChar((char)0);
        }
        else
        {
            Password.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBoxShowPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogin_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JCheckBox jCheckBoxShowPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAdminId;
    private javax.swing.JLabel jLabelBackButton;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelCopyrightText;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
