/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package digital_office_management_system;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.border.Border;

/**
 *
 * @author USER
 */
public class AdminOrStaff_form extends javax.swing.JFrame {

    /**
     * Creates new form AdminOrStaff_form
     */
    public AdminOrStaff_form() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        // create a border with the color of the parent jpanel for the icons label to remove the move
        Border label_icons_border = BorderFactory.createMatteBorder(2, 2, 2, 2, new Color(149,165,166));
        jLabelAdmin.setBorder(label_icons_border);
        jLabelStaff.setBorder(label_icons_border);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelAdmin = new javax.swing.JLabel();
        jLabelStaff = new javax.swing.JLabel();
        jLabelStaffText = new javax.swing.JLabel();
        jLabelAdminText = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jLabelCopyrightText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabelAdmin.setBackground(new java.awt.Color(153, 153, 153));
        jLabelAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Admin.png"))); // NOI18N
        jLabelAdmin.setOpaque(true);
        jPanel1.add(jLabelAdmin);
        jLabelAdmin.setBounds(170, 290, 148, 148);

        jLabelStaff.setBackground(new java.awt.Color(153, 153, 153));
        jLabelStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Staff.png"))); // NOI18N
        jLabelStaff.setOpaque(true);
        jPanel1.add(jLabelStaff);
        jLabelStaff.setBounds(390, 290, 148, 148);

        jLabelStaffText.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelStaffText.setText("Staff");
        jLabelStaffText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelStaffTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelStaffTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelStaffTextMouseExited(evt);
            }
        });
        jPanel1.add(jLabelStaffText);
        jLabelStaffText.setBounds(440, 450, 70, 20);

        jLabelAdminText.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelAdminText.setText("Admin");
        jLabelAdminText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAdminTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelAdminTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelAdminTextMouseExited(evt);
            }
        });
        jPanel1.add(jLabelAdminText);
        jLabelAdminText.setBounds(220, 450, 70, 20);

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelClose.setText(" X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseExited(evt);
            }
        });
        jPanel1.add(jLabelClose);
        jLabelClose.setBounds(660, 10, 20, 22);

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMin.setText(" -");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMinMouseExited(evt);
            }
        });
        jPanel1.add(jLabelMin);
        jLabelMin.setBounds(630, 10, 20, 22);

        jLabelCopyrightText.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCopyrightText.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelCopyrightText.setForeground(new java.awt.Color(153, 153, 153));
        jLabelCopyrightText.setText("Copyright 2019 - Digital Office Management System | All Rights Reserved TO US");
        jPanel1.add(jLabelCopyrightText);
        jLabelCopyrightText.setBounds(90, 630, 530, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AdminOrStaff.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 680);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelAdminTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAdminTextMouseEntered
        jLabelAdminText.setForeground(Color.gray);
    }//GEN-LAST:event_jLabelAdminTextMouseEntered

    private void jLabelAdminTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAdminTextMouseExited
        jLabelAdminText.setForeground(Color.black);
    }//GEN-LAST:event_jLabelAdminTextMouseExited

    private void jLabelStaffTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelStaffTextMouseEntered
        jLabelStaffText.setForeground(Color.gray);
    }//GEN-LAST:event_jLabelStaffTextMouseEntered

    private void jLabelStaffTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelStaffTextMouseExited
        jLabelStaffText.setForeground(Color.black);
    }//GEN-LAST:event_jLabelStaffTextMouseExited

    private void jLabelStaffTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelStaffTextMouseClicked
        Login_form lgf = new Login_form();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelStaffTextMouseClicked

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseEntered
        jLabelClose.setForeground(Color.red);
    }//GEN-LAST:event_jLabelCloseMouseEntered

    private void jLabelCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseExited
        jLabelClose.setForeground(Color.black);
    }//GEN-LAST:event_jLabelCloseMouseExited

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jLabelMinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseEntered
        jLabelMin.setForeground(Color.gray);
    }//GEN-LAST:event_jLabelMinMouseEntered

    private void jLabelMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseExited
        jLabelMin.setForeground(Color.black);
    }//GEN-LAST:event_jLabelMinMouseExited

    private void jLabelAdminTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAdminTextMouseClicked
        AdminLogin_form adlgf = new AdminLogin_form();
        adlgf.setVisible(true);
        adlgf.pack();
        adlgf.setLocationRelativeTo(null);
        adlgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelAdminTextMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminOrStaff_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminOrStaff_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminOrStaff_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminOrStaff_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminOrStaff_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAdmin;
    private javax.swing.JLabel jLabelAdminText;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelCopyrightText;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabelStaff;
    private javax.swing.JLabel jLabelStaffText;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
