/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package digital_office_management_system;

import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author USER
 */
public class Signup_form extends javax.swing.JFrame {
java.util.Date date;
java.sql.Date sqldate;
    /**
     * Creates new form Signup_form
     */
    String image_path = null;
    public Signup_form() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        // create a button group for the radiobuttons
        ButtonGroup bg = new ButtonGroup();
        bg.add(jRadioButtonMale);
        bg.add(jRadioButtonFemale);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelMin = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        jLabelUsername = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        jLabelPassword = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        jLabelRetype_password = new javax.swing.JLabel();
        Retype_password = new javax.swing.JPasswordField();
        jLabelGender = new javax.swing.JLabel();
        jRadioButtonMale = new javax.swing.JRadioButton();
        jRadioButtonFemale = new javax.swing.JRadioButton();
        jLabelBirthDate = new javax.swing.JLabel();
        BirthDate = new com.toedter.calendar.JDateChooser();
        jLabelPhoneNo = new javax.swing.JLabel();
        PhoneNo = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabelImage = new javax.swing.JLabel();
        jButtonSelectImage = new javax.swing.JButton();
        jLabelImagePath = new javax.swing.JLabel();
        jButtonSignup = new javax.swing.JButton();
        jLabelLogin = new javax.swing.JLabel();
        jLabelCopyrightText = new javax.swing.JLabel();
        jLabelDepartment = new javax.swing.JLabel();
        Department = new javax.swing.JTextField();
        jLabelBasic = new javax.swing.JLabel();
        Basic = new javax.swing.JTextField();
        jLabelHiredDate = new javax.swing.JLabel();
        HiredDate = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMin.setText(" -");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMinMouseExited(evt);
            }
        });
        jPanel1.add(jLabelMin);
        jLabelMin.setBounds(630, 10, 20, 22);

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelClose.setText(" X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseExited(evt);
            }
        });
        jPanel1.add(jLabelClose);
        jLabelClose.setBounds(660, 10, 20, 22);

        jLabelId.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        jLabelId.setForeground(new java.awt.Color(0, 102, 204));
        jLabelId.setText("StaffID:");
        jPanel1.add(jLabelId);
        jLabelId.setBounds(30, 260, 90, 30);

        ID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ID.setForeground(new java.awt.Color(153, 153, 153));
        ID.setText("XX-XX-XX-XXX");
        ID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                IDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                IDFocusLost(evt);
            }
        });
        jPanel1.add(ID);
        ID.setBounds(180, 260, 180, 30);

        jLabelUsername.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        jLabelUsername.setForeground(new java.awt.Color(0, 102, 204));
        jLabelUsername.setText("Staff Name:");
        jPanel1.add(jLabelUsername);
        jLabelUsername.setBounds(30, 300, 120, 30);

        Username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Username.setForeground(new java.awt.Color(153, 153, 153));
        Username.setText("username");
        Username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UsernameFocusLost(evt);
            }
        });
        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });
        jPanel1.add(Username);
        Username.setBounds(180, 300, 180, 30);

        jLabelPassword.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(0, 102, 204));
        jLabelPassword.setText("Password:");
        jPanel1.add(jLabelPassword);
        jLabelPassword.setBounds(30, 340, 120, 28);

        Password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Password.setForeground(new java.awt.Color(153, 153, 153));
        Password.setText("password");
        Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordFocusLost(evt);
            }
        });
        jPanel1.add(Password);
        Password.setBounds(180, 340, 180, 30);

        jLabelRetype_password.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        jLabelRetype_password.setForeground(new java.awt.Color(0, 102, 204));
        jLabelRetype_password.setText("Retype Pass:");
        jPanel1.add(jLabelRetype_password);
        jLabelRetype_password.setBounds(30, 380, 130, 30);

        Retype_password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Retype_password.setForeground(new java.awt.Color(153, 153, 153));
        Retype_password.setText("password");
        Retype_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Retype_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Retype_passwordFocusLost(evt);
            }
        });
        jPanel1.add(Retype_password);
        Retype_password.setBounds(180, 380, 180, 30);

        jLabelGender.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        jLabelGender.setForeground(new java.awt.Color(0, 102, 204));
        jLabelGender.setText("Gender:");
        jPanel1.add(jLabelGender);
        jLabelGender.setBounds(30, 420, 90, 30);

        jRadioButtonMale.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonMale.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jRadioButtonMale.setSelected(true);
        jRadioButtonMale.setText("Male");
        jRadioButtonMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMaleActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonMale);
        jRadioButtonMale.setBounds(190, 423, 70, 27);

        jRadioButtonFemale.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonFemale.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jRadioButtonFemale.setText("Female");
        jPanel1.add(jRadioButtonFemale);
        jRadioButtonFemale.setBounds(270, 423, 80, 27);

        jLabelBirthDate.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        jLabelBirthDate.setForeground(new java.awt.Color(0, 102, 204));
        jLabelBirthDate.setText("Birth Date:");
        jPanel1.add(jLabelBirthDate);
        jLabelBirthDate.setBounds(30, 460, 120, 30);

        BirthDate.setForeground(new java.awt.Color(153, 153, 153));
        BirthDate.setToolTipText("");
        BirthDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(BirthDate);
        BirthDate.setBounds(180, 460, 180, 30);

        jLabelPhoneNo.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        jLabelPhoneNo.setForeground(new java.awt.Color(0, 102, 204));
        jLabelPhoneNo.setText("Phone No:");
        jPanel1.add(jLabelPhoneNo);
        jLabelPhoneNo.setBounds(380, 260, 110, 30);

        PhoneNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PhoneNo.setForeground(new java.awt.Color(153, 153, 153));
        PhoneNo.setText("01X-XXX-XXX-XX");
        PhoneNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PhoneNoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PhoneNoFocusLost(evt);
            }
        });
        jPanel1.add(PhoneNo);
        PhoneNo.setBounds(520, 260, 150, 30);

        jLabelEmail.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(0, 102, 204));
        jLabelEmail.setText("Email:");
        jPanel1.add(jLabelEmail);
        jLabelEmail.setBounds(380, 300, 70, 30);

        Email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Email.setForeground(new java.awt.Color(153, 153, 153));
        Email.setText("abcd@gmail.com");
        Email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                EmailFocusLost(evt);
            }
        });
        jPanel1.add(Email);
        Email.setBounds(520, 300, 150, 30);

        jLabelImage.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        jLabelImage.setForeground(new java.awt.Color(0, 102, 204));
        jLabelImage.setText("Image:");
        jPanel1.add(jLabelImage);
        jLabelImage.setBounds(380, 460, 80, 30);

        jButtonSelectImage.setText("Select Image");
        jButtonSelectImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectImageActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSelectImage);
        jButtonSelectImage.setBounds(547, 470, 120, 20);

        jLabelImagePath.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        jLabelImagePath.setText("image path");
        jPanel1.add(jLabelImagePath);
        jLabelImagePath.setBounds(540, 500, 130, 20);

        jButtonSignup.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSignup.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonSignup.setForeground(new java.awt.Color(0, 153, 0));
        jButtonSignup.setText("Sign Up");
        jButtonSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSignupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSignupMouseExited(evt);
            }
        });
        jButtonSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSignupActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSignup);
        jButtonSignup.setBounds(170, 510, 350, 50);

        jLabelLogin.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelLogin.setText("Click here to login");
        jLabelLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelLoginMouseExited(evt);
            }
        });
        jPanel1.add(jLabelLogin);
        jLabelLogin.setBounds(290, 560, 130, 30);

        jLabelCopyrightText.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCopyrightText.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelCopyrightText.setForeground(new java.awt.Color(153, 153, 153));
        jLabelCopyrightText.setText("Copyright 2019 - Digital Office Management System | All Rights Reserved TO US");
        jPanel1.add(jLabelCopyrightText);
        jLabelCopyrightText.setBounds(90, 630, 530, 30);

        jLabelDepartment.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        jLabelDepartment.setForeground(new java.awt.Color(0, 102, 204));
        jLabelDepartment.setText("Department:");
        jPanel1.add(jLabelDepartment);
        jLabelDepartment.setBounds(380, 340, 130, 30);

        Department.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Department.setForeground(new java.awt.Color(153, 153, 153));
        Department.setText("sales");
        Department.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DepartmentFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DepartmentFocusLost(evt);
            }
        });
        jPanel1.add(Department);
        Department.setBounds(520, 340, 150, 30);

        jLabelBasic.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        jLabelBasic.setForeground(new java.awt.Color(0, 102, 204));
        jLabelBasic.setText("Basic Salary:");
        jPanel1.add(jLabelBasic);
        jLabelBasic.setBounds(380, 420, 130, 30);

        Basic.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Basic.setForeground(new java.awt.Color(153, 153, 153));
        Basic.setText("1XX-XX");
        Basic.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BasicFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                BasicFocusLost(evt);
            }
        });
        jPanel1.add(Basic);
        Basic.setBounds(520, 420, 150, 30);

        jLabelHiredDate.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        jLabelHiredDate.setForeground(new java.awt.Color(0, 102, 204));
        jLabelHiredDate.setText("Date Hired:");
        jPanel1.add(jLabelHiredDate);
        jLabelHiredDate.setBounds(380, 380, 130, 30);

        HiredDate.setForeground(new java.awt.Color(153, 153, 153));
        HiredDate.setToolTipText("");
        HiredDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(HiredDate);
        HiredDate.setBounds(520, 380, 150, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/signup.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 702, 680);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jLabelLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLoginMouseClicked
        Login_form lgf = new Login_form();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelLoginMouseClicked

    private void jLabelMinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseEntered
        jLabelMin.setForeground(Color.gray);
    }//GEN-LAST:event_jLabelMinMouseEntered

    private void jLabelMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseExited
        jLabelMin.setForeground(Color.black);
    }//GEN-LAST:event_jLabelMinMouseExited

    private void jLabelCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseEntered
        jLabelClose.setForeground(Color.red);
    }//GEN-LAST:event_jLabelCloseMouseEntered

    private void jLabelCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseExited
        jLabelClose.setForeground(Color.black);
    }//GEN-LAST:event_jLabelCloseMouseExited

    private void UsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFocusGained
        // clear the textfield on focus if the text is "username"
        if(Username.getText().trim().toLowerCase().equals("username"))
        {
            Username.setText("");
            Username.setForeground(Color.black);
        }
    }//GEN-LAST:event_UsernameFocusGained

    private void UsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFocusLost
        // if the text field is equal to username or empty
        // we will set the "username" text in the field 
        // on focus lost event
        if(Username.getText().trim().equals("") || Username.getText().trim().toLowerCase().equals("username"))
        {
            Username.setText("username");
            Username.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_UsernameFocusLost

    private void PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusGained
        // clear the password field on focus if the text is "password"       
        // get the password text
        String pass = String.valueOf(Password.getPassword());        
        if(pass.trim().toLowerCase().equals("password"))
        {
            Password.setText("");
            Password.setForeground(Color.black);
        }
    }//GEN-LAST:event_PasswordFocusGained

    private void PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusLost
        // if the password field is equal to password or empty
        // we will set the "password" text in the field 
        // on focus lost event        
        // get the password text
        String pass = String.valueOf(Password.getPassword());        
        if(pass.trim().equals("") || pass.trim().toLowerCase().equals("password"))
        {
            Password.setText("password");
            Password.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_PasswordFocusLost

    private void Retype_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Retype_passwordFocusGained
        // clear the password field on focus if the text is "password"       
        // get the password text
        String pass = String.valueOf(Retype_password.getPassword());        
        if(pass.trim().toLowerCase().equals("password"))
        {
            Retype_password.setText("");
            Retype_password.setForeground(Color.black);
        }
    }//GEN-LAST:event_Retype_passwordFocusGained

    private void Retype_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Retype_passwordFocusLost
        // if the password field is equal to password or empty
        // we will set the "password" text in the field 
        // on focus lost event        
        // get the password text
        String pass = String.valueOf(Retype_password.getPassword());        
        if(pass.trim().equals("") || pass.trim().toLowerCase().equals("password"))
        {
            Retype_password.setText("password");
            Retype_password.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_Retype_passwordFocusLost

    private void jButtonSignupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSignupMouseEntered
        // set jbutton background
        jButtonSignup.setBackground(new Color(149,165,166));
    }//GEN-LAST:event_jButtonSignupMouseEntered

    private void jButtonSignupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSignupMouseExited
        // set jbutton background
        jButtonSignup.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_jButtonSignupMouseExited

    private void jLabelLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLoginMouseEntered
        jLabelLogin.setForeground(Color.gray);
    }//GEN-LAST:event_jLabelLoginMouseEntered

    private void jLabelLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLoginMouseExited
        jLabelLogin.setForeground(Color.black);
    }//GEN-LAST:event_jLabelLoginMouseExited

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    private void jButtonSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSignupActionPerformed
        String id = ID.getText();        
        String username = Username.getText();
        String pass1 = String.valueOf(Password.getPassword());
        String pass2 = String.valueOf(Retype_password.getPassword());
        String gender = "Male";
        String bdate = null;
        String phone = PhoneNo.getText();
        String email = Email.getText();
        String dept = Department.getText();
        String hdate = null;
        String bsalary = Basic.getText();
        String yr = null;
        
        //check if BirthDate feild is empty
        if(BirthDate.getDate() != null)
        {
           SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
           bdate = sdf.format(BirthDate.getDate());
        }
        
        //check if HiredDate feild is empty
        if(HiredDate.getDate() != null)
        {
           SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
           hdate = sdf.format(HiredDate.getDate());
           yr = hdate.substring(6);
        }
        
        if(jRadioButtonFemale.isSelected()){
             gender = "Female";
        }
        
        // check if the data are empty
        if(verifyFields())
        {
            // check if the id already exists
            if(!checkId(id))
            {
                PreparedStatement ps;
                ResultSet rs;
                String registerUserQuery = "INSERT INTO `staffs`(`ID`, `Username`, `Password`, `Gender`, `Birth Date`, `Phone No`, `Email`, `Department`, `Hired Date`, `Basic Salary`, `Picture`) VALUES (?,?,?,?,?,?,?,?,?,?,?)";
                
                try {
                    ps = MyConnection.getConnection().prepareStatement(registerUserQuery);
                    ps.setString(1, id);
                    ps.setString(2, username);
                    ps.setString(3, pass1);
                    ps.setString(4, gender);
                    ps.setString(5, bdate);
                    if(bdate != null)
                    {
                        ps.setString(5, bdate);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Enter your Birthdate","Empty Birthdate",2);
                    }                            
                    ps.setString(6, phone);
                    if(!checkEmail(email))
                    {
                        ps.setString(7, email); 
                    }
                    ps.setString(8, dept);
                    ps.setString(9, hdate);
                    if(hdate != null)
                    {
                        ps.setString(9, hdate);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Enter your Hired date","Empty Hired date",2);
                    }
                    ps.setString(10, bsalary);
                                       
                    try {
                        // save the image as blob in the database
                        if(image_path != null)
                        {
                            InputStream image = new FileInputStream(new File(image_path));
                            ps.setBlob(11, image);
                        } else {
                            ps.setNull(11, java.sql.Types.NULL);
                        }                        
                        
                        if (ps.executeUpdate() != 0) {
                            JOptionPane.showMessageDialog(null, "Your Account Has Been Created");
                            ID.setText("");
                            Username.setText("");
                            Password.setText("");
                            Retype_password.setText("");
                            PhoneNo.setText("");
                            Email.setText("");
                            Department.setText("");
                            Basic.setText("");
                        } else {
                            JOptionPane.showMessageDialog(null, "Error: Check Your Information");
                        }
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(Signup_form.class.getName()).log(Level.SEVERE, null, ex);
                    }                    
                } catch (SQLException ex) {
                    Logger.getLogger(Signup_form.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        Date currentDate = GregorianCalendar.getInstance().getTime();
        DateFormat df = DateFormat.getDateInstance();
        String dateString = df.format(currentDate);

        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
        String timeString = sdf.format(d);

        String value0 = timeString;
        String value1 = dateString;
        String date = value0 + " / " + value1;
        String status = "Added Record";

        try{
            PreparedStatement ps;
            ResultSet rs;
            String reg = "INSERT INTO `audit`(`Emp_ID`, `Date`, `Status`) VALUES (?,?,?)";
            ps = MyConnection.getConnection().prepareStatement(reg);
            ps.setString(1, id);
            ps.setString(2, date);
            ps.setString(3, status);
            ps.executeUpdate();
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
        String cas = "10";
        String ann = "10";
        String med = "10";
        
        try{
            PreparedStatement ps;
            ResultSet rs;
            String leave = "INSERT INTO `leaves`(`Emp_ID`, `Casual`, `Annual`, `Medical`, `Year`) VALUES (?,?,?,?,?)";
            ps = MyConnection.getConnection().prepareStatement(leave);
            ps.setString(1, id);
            ps.setString(2, cas);
            ps.setString(3, ann);
            ps.setString(4, med);
            ps.setString(5, yr);
            ps.executeUpdate();
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButtonSignupActionPerformed

    private void jRadioButtonMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMaleActionPerformed

    private void IDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDFocusGained
        // clear the textfield on focus if the text is "XX-XX-XX-XXX"
        if(ID.getText().trim().toUpperCase().equals("XX-XX-XX-XXX"))
        {
            ID.setText("");
            ID.setForeground(Color.black);
        }
    }//GEN-LAST:event_IDFocusGained

    private void IDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDFocusLost
        // if the text field is equal to XX-XX-XX-XXX or empty
        // we will set the "XX-XX-XX-XXX" text in the field 
        // on focus lost event
        if(ID.getText().trim().equals("") || ID.getText().trim().toUpperCase().equals("XX-XX-XX-XXX"))
        {
            ID.setText("XX-XX-XX-XXX");
            ID.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_IDFocusLost

    private void PhoneNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PhoneNoFocusGained
        // clear the textfield on focus if the text is "01X-XXX-XXX-XX"
        if(PhoneNo.getText().trim().toUpperCase().equals("01X-XXX-XXX-XX"))
        {
            PhoneNo.setText("");
            PhoneNo.setForeground(Color.black);
        }
    }//GEN-LAST:event_PhoneNoFocusGained

    private void PhoneNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PhoneNoFocusLost
        // if the text field is equal to 01X-XXX-XXX-XX or empty
        // we will set the "01X-XXX-XXX-XX" text in the field 
        // on focus lost event
        if(PhoneNo.getText().trim().equals("") || PhoneNo.getText().trim().toUpperCase().equals("01X-XXX-XXX-XX"))
        {
            PhoneNo.setText("01X-XXX-XXX-XX");
            PhoneNo.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_PhoneNoFocusLost

    private void EmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailFocusGained
        // clear the textfield on focus if the text is "abcd@gmail.com"
        if(Email.getText().trim().toLowerCase().equals("abcd@gmail.com"))
        {
            Email.setText("");
            Email.setForeground(Color.black);
        }
    }//GEN-LAST:event_EmailFocusGained

    private void EmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailFocusLost
        // if the text field is equal to "abcd@gmail.com" or empty
        // we will set the "abcd@gmail.com" text in the field 
        // on focus lost event
        if(Email.getText().trim().equals("") || Email.getText().trim().toUpperCase().equals("abcd@gmail.com"))
        {
            Email.setText("abcd@gmail.com");
            Email.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_EmailFocusLost

    private void jButtonSelectImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectImageActionPerformed
        // select an image and set the image path into a jlabel
        String path = null;
        
        JFileChooser chooser = new JFileChooser();
        
        chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        
        // file extension
        FileNameExtensionFilter extension = new FileNameExtensionFilter("*.Images","jpg","png","jpeg");
        chooser.addChoosableFileFilter(extension);
        
        int filestate = chooser.showSaveDialog(null);
        
        // check if the user select an image
        if(filestate == JFileChooser.APPROVE_OPTION){
            
            File selectedImage = chooser.getSelectedFile();
            path = selectedImage.getAbsolutePath();
            jLabelImagePath.setText(path);
            
            image_path = path;
        }
    }//GEN-LAST:event_jButtonSelectImageActionPerformed

    private void DepartmentFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DepartmentFocusGained
        // clear the textfield on focus if the text is "sales"
        if(Department.getText().trim().toLowerCase().equals("sales"))
        {
            Department.setText("");
            Department.setForeground(Color.black);
        }
    }//GEN-LAST:event_DepartmentFocusGained

    private void DepartmentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DepartmentFocusLost
        // if the text field is equal to "sales" or empty
        // we will set the "Sales" text in the field 
        // on focus lost event
        if(Department.getText().trim().equals("") || Department.getText().trim().toUpperCase().equals("sales"))
        {
            Department.setText("sales");
            Department.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_DepartmentFocusLost

    private void BasicFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BasicFocusGained
        // clear the textfield on focus if the text is "1XX-XX"
        if(Basic.getText().trim().toUpperCase().equals("1XX-XX"))
        {
            Basic.setText("");
            Basic.setForeground(Color.black);
        }
    }//GEN-LAST:event_BasicFocusGained

    private void BasicFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BasicFocusLost
        // if the text field is equal to "1XX-XX" or empty
        // we will set the "1XX-XX" text in the field 
        // on focus lost event
        if(Basic.getText().trim().equals("") || Basic.getText().trim().toUpperCase().equals("1XX-XX"))
        {
            Basic.setText("1XX-XX");
            Basic.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_BasicFocusLost

    // create a function to verify the empty fields  
    public boolean verifyFields()
    {
        String id = ID.getText();
        String uname = Username.getText();
        String pass1 = String.valueOf(Password.getPassword());
        String pass2 = String.valueOf(Retype_password.getPassword());
        String phone = PhoneNo.getText();
        String email = Email.getText();
        String check = "@gmail.com";
        
        // check if id is empty fields
        if(id.trim().equals("") || pass1.trim().equals("XX-XX-XX-XXX"))
        {
            JOptionPane.showMessageDialog(null, "Enter your ID","Empty Fields",2);
            return false;
        }
        // check if password is empty fields
        else if(pass1.trim().equals("") || pass1.trim().equals("password") || pass2.trim().equals("") || pass2.trim().equals("password"))  
        {
            JOptionPane.showMessageDialog(null, "Enter your Password","Empty Fields",2);
            return false;
        }
        // check if username is empty fields
        else if(uname.trim().equals("") || uname.trim().equals("username"))  
        {
            JOptionPane.showMessageDialog(null, "Enter your Username","Empty Fields",2);
            return false;
        }
        // check if phone no is empty fields
        else if(phone.trim().equals("") || phone.trim().equals("01X-XXX-XXX-XX"))  
        {
            JOptionPane.showMessageDialog(null, "Enter your Phone No","Empty Fields",2);
            return false;
        }
        // check if email is empty fields
        else if(email.trim().equals("") || email.trim().equals("abcd@gmail.com"))  
        {
            JOptionPane.showMessageDialog(null, "Enter your Email","Empty Fields",2);
            return false;
        }
        // check if the two password are equals or not
        else if(!pass1.equals(pass2))
        {
            JOptionPane.showMessageDialog(null, "Password Doesn't Match","Confirm Password",2); 
            Password.setText("");
            Retype_password.setText("");
            return false;
        }
        else if(!email.contains(check))
        {
            JOptionPane.showMessageDialog(null, "Email invalid format","Confirm Email",2);
            return false;
        }
        // if everything is ok
        else{
            return true;
        }
    }
    
    // create a function to check if the entered id is already exists in the database
    public boolean checkId(String id){
        
        PreparedStatement st;
        ResultSet rs;
        boolean id_exist = false;
        
        String query = "SELECT * FROM `staffs` WHERE `ID` = ?";
        
        try {
            
            st = MyConnection.getConnection().prepareStatement(query);
            st.setString(1, id);
            rs = st.executeQuery();
        
            if(rs.next())
            {
                id_exist = true;
                JOptionPane.showMessageDialog(null, "This Id is Already Taken, Choose Another One", "ID Failed", 2);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Signup_form.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return id_exist;
    }
    
    // create a function to check if the entered email is already exists in the database
    public boolean checkEmail(String email){
        
        PreparedStatement st;
        ResultSet rs;
        boolean email_exist = false;
        
        String query = "SELECT * FROM `staffs` WHERE `Email` = ?";
        
        try {
            
            st = MyConnection.getConnection().prepareStatement(query);
            st.setString(1, email);
            rs = st.executeQuery();
        
            if(rs.next())
            {
                email_exist = true;
                JOptionPane.showMessageDialog(null, "This Email is Already Taken, Choose Another One", "Email Failed", 2);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Signup_form.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return email_exist;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Basic;
    private com.toedter.calendar.JDateChooser BirthDate;
    private javax.swing.JTextField Department;
    private javax.swing.JTextField Email;
    private com.toedter.calendar.JDateChooser HiredDate;
    private javax.swing.JTextField ID;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField PhoneNo;
    private javax.swing.JPasswordField Retype_password;
    private javax.swing.JTextField Username;
    private javax.swing.JButton jButtonSelectImage;
    private javax.swing.JButton jButtonSignup;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBasic;
    private javax.swing.JLabel jLabelBirthDate;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelCopyrightText;
    private javax.swing.JLabel jLabelDepartment;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelGender;
    private javax.swing.JLabel jLabelHiredDate;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelImagePath;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelPhoneNo;
    private javax.swing.JLabel jLabelRetype_password;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonFemale;
    private javax.swing.JRadioButton jRadioButtonMale;
    // End of variables declaration//GEN-END:variables
}
